# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-21.25

packages:
- accelerate-llvm
- accelerate-llvm-native
- accelerate-llvm-ptx

extra-deps:
- cuda-0.11.0.1
- nvvm-0.10.0.1
- OptDir-0.0.4
- bytestring-encoding-0.1.2.0
- ../accelerate
- MIP-0.2.0.0

- github: tomsmeding/llvm-pretty
  commit: 16fb617f282bde97a090b8b08cbd2dcf5e259ad3

- monadLib-3.10.3@sha256:026ba169762e63f0fe5f5c78829808f522a28730043bc3ad9b7c146baedf709f,637

# Override default flag values for local packages and extra-deps
# flags:

# Extra per-package and global ghc options
# ghc-options:
#   llvm-hs: -optcxx=-std=c++14 -optcxx=-lstdc++ -optcxx=-fno-rtti

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.9"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
#
# vim: nospell
