{-# LANGUAGE CPP             #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -Wno-unused-imports   #-}
{-# OPTIONS_GHC -Wno-unused-top-binds #-}
-- |
-- Module      : Data.Array.Accelerate.LLVM.Native.Plugin
-- Copyright   : [2017..2020] The Accelerate Team
-- License     : BSD3
--
-- Maintainer  : Trevor L. McDonell <trevor.mcdonell@gmail.com>
-- Stability   : experimental
-- Portability : non-portable (GHC extensions)
--

module Data.Array.Accelerate.LLVM.Native.Plugin (

  plugin,

) where

import Data.Array.Accelerate.Error
import Data.Array.Accelerate.LLVM.Native.Plugin.Annotation
import Data.Array.Accelerate.LLVM.Native.Plugin.BuildInfo

import Control.Monad
import Data.IORef
import Data.List                                                    ( nub )
import qualified Data.Map                                           as Map

import GHC.Driver.Backend
#if __GLASGOW_HASKELL__ < 910
import GHC.Linker
#endif
import GHC.Linker.Loader                                            ( loadCmdLineLibs )
import GHC.Plugins
import GHC.Runtime.Interpreter


-- | This GHC plugin is required to support ahead-of-time compilation for the
-- accelerate-llvm-native backend. In particular, it tells GHC about the
-- additional object files generated by
-- 'Data.Array.Accelerate.LLVM.Native.runQ'* which must be linked into the final
-- executable.
--
-- This plugin is automatically installed when using runQ. In older versions of
-- GHC, it was necessary to manually add the plugin using:
--
-- > ghc-options: -fplugin=Data.Array.Accelerate.LLVM.Native.Plugin
--
-- That is no longer needed.

--
plugin :: Plugin
plugin = defaultPlugin
  { installCoreToDos = install
  , pluginRecompile  = purePlugin
  }

install :: HasCallStack => [CommandLineOption] -> [CoreToDo] -> CoreM [CoreToDo]
install _ rest = do
  let this (CoreDoPluginPass "accelerate-llvm-native" _) = True
      this _                                             = False
  --
  return $ CoreDoPluginPass "accelerate-llvm-native" pass : filter (not . this) rest

pass :: HasCallStack => ModGuts -> CoreM ModGuts
pass guts = do
  -- Gather annotations for the extra object files which must be supplied to the
  -- linker in order to complete the current module.
  --
  this  <- getModule
  paths <- nub . concat <$> mapM (objectPaths guts) (mg_binds guts)

  unless (null paths)
    $ debugTraceMsg
    $ hang (text "Data.Array.Accelerate.LLVM.Native.Plugin: linking module" <+> quotes (pprModule this) <+> text "with:") 2 (vcat (map text paths))

  -- The linking method depends on the current build target
  -- TODO: Need to update for ghc-8.6: the Backend data type is now abstract
  --
  -- Determine the current build environment
  --
  hscEnv   <- getHscEnv
  dynFlags <- getDynFlags

  let target = backend dynFlags

  when (backendGeneratesCode target) $
    if backendWritesFiles target
      then
        -- The compiler will write files (interface files and object code). This
        -- is true of "real" backends, i.e. not the interpreter.
        return ()

      else
        -- We are in interactive mode (ghci)
        unless (null paths) . liftIO $ do
          let opts  = ldInputs dynFlags
              objs  = map optionOfPath paths
          loadCmdLineLibs (hscInterp hscEnv)
                 $ hscEnv { hsc_dflags = dynFlags { ldInputs = opts ++ objs }}
  return guts

#if __GLASGOW_HASKELL__ < 906
backendGeneratesCode :: Backend -> Bool
backendGeneratesCode NoBackend = False
backendGeneratesCode _         = True

backendWritesFiles :: Backend -> Bool
backendWritesFiles Interpreter = False
backendWritesFiles _           = True
#endif

objectPaths :: ModGuts -> CoreBind -> CoreM [FilePath]
objectPaths guts (NonRec b _) = objectAnns guts b
objectPaths guts (Rec bs)     = concat <$> mapM (objectAnns guts . fst) bs

objectAnns :: ModGuts -> CoreBndr -> CoreM [FilePath]
objectAnns guts bndr = do
  anns  <- getAnnotations deserializeWithData guts
  return [ path | Object path <- lookupWithDefaultUFM (snd anns) [] (varName bndr) ]

objectMapPath :: DynFlags -> FilePath
objectMapPath DynFlags{..}
  | Just p <- objectDir = p
  | Just p <- dumpDir   = p
  | otherwise           = "."

optionOfPath :: FilePath -> Option
optionOfPath = FileOption []

